### ISSUE TITLE
Warning about incompatible version of Microsoft.EntityFrameworkCore.Design 3.0.0

### ISSUE THREAD

**Issue by cezarypiatek** [lkurzyniec/netcore-boilerplate#1]
I'm getting the following warning during the build.

```plaintext
warning NU1701: Package 'Microsoft.EntityFrameworkCore.Design 3.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. 
This package may not be fully compatible with your project.
```
Because this supposes to be a role model repository it should avoid warnings during the build. 
I'm not familiar with EF so I have no idea what this package is responsible for but it looks like it was not designed for .net core 3.0.

**Comment by lkurzyniec** [comment]
I don't remember why .net forced me to add this package. Maybe for scaffolding, I'm not sure.
Anyway, It's redundant for now, removing it, thx.

**Comment by lkurzyniec** [comment]
Removed in 760dabdcb540c9d9ee542f76c9cfa99aefd07db8
