### ISSUE TITLE
Dependency Resolution Exception

### ISSUE THREAD

**Issue by weihan1394** [lkurzyniec/netcore-boilerplate#12]
Hi,

I have forked out your repository as a boilerplate and added npgsql to support postgres database. However, I am facing an "Autofac.Core.DependencyResolutionException" error even though I have injected the dependency at `GeneralRegisterModule` file. Did I inject the repository wrongly?

The flow that I am trying to implement is 
**Controller** --> **Service** --> **Repository**

**Error**
`"Autofac.Core.DependencyResolutionException: An exception was thrown while activating ShippingService.Core.Services.ShippingRateService.\r\n ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'ShippingService.Core.Services.ShippingRateService' can be invoked with the available services and parameters:\r\nCannot resolve parameter 'ShippingService.Core.Repositories.ShippingExpressRepository shippingExpressRepository' of constructor 'Void .ctor(ShippingService.Core.Repositories.ShippingExpressRepository)'.`

**GeneralRegisterModule.cs**
`builder.RegisterType<ShippingExpressRepository>().As<IShippingExpressRepository>();
builder.RegisterType<ShippingRateService>().As<IShippingRateService>();`

**ShippingRateService**
`
 private readonly IShippingExpressRepository _shippingExpressRepository;

public ShippingRateService(ShippingExpressRepository shippingExpressRepository)
{
        _shippingExpressRepository = shippingExpressRepository;
}
`

**Comment by lkurzyniec** [comment]
@weihan1394 it looks like autofac has a problem with `ShippingExpressRepository`, check its constructor. As I assume, repo takes either dbcontext or abstraction. Have you registered that?

**Comment by weihan1394** [comment]
@lkurzyniec Thank you for your help in advance.

I am using the dbcontext based on how u have registered the EmployeeRepository.
Do correct me wrong if I understood wrongly, I register the repository at the **GeneralRegisterModule.cs** right?

[Snippet](https://gist.github.com/weihan1394/8d8d24097597b0326a9985abcfb0d212)

**Comment by lkurzyniec** [comment]
@weihan1394 yes, Repository should be registered in `GeneralRegisterModule.cs`, but remember to also register `DbContext` in `Startup.cs` file, like I did: `services.AddDbContext<EmployeesContext>(options => options.UseMySql(_configuration.GetConnectionString("MySqlDb")));`.

To show you what could be wrong, I removed above registration from `Startup.cs` file and then I got this exception:
```
Autofac.Core.DependencyResolutionException: An exception was thrown while activating HappyCode.NetCoreBoilerplate.Core.Repositories.EmployeeRepository.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'HappyCode.NetCoreBoilerplate.Core.Repositories.EmployeeRepository' can be invoked with the available services and parameters:
Cannot resolve parameter 'HappyCode.NetCoreBoilerplate.Core.EmployeesContext dbContext' of constructor 'Void .ctor(HappyCode.NetCoreBoilerplate.Core.EmployeesContext)'.
```
As you can see, it's quite similar to yours, so please double check your registration of `DbContext` in `Startup.cs` file.

**Comment by weihan1394** [comment]
@lkurzyniec Yup, I did that too just like this. 
[startup.cs](https://gist.github.com/weihan1394/8d8d24097597b0326a9985abcfb0d212#file-startup-cs)

I'm wondering could there be a problem with my DbContext? But I tested by changing the carscontext to a more simplified one that works with the postgresdb.

[ShippingExpressContext.cs](https://gist.github.com/weihan1394/8d8d24097597b0326a9985abcfb0d212#file-shippingexpresscontext-cs)

**Comment by lkurzyniec** [comment]
@weihan1394 no problem, I can try to reproduce your problem at the weekend.

**Comment by weihan1394** [comment]
@lkurzyniec Thank you for the help. Definitely it helps!

**Comment by lkurzyniec** [comment]
@weihan1394 I can't see it.
![Screenshot_20200613-171124~2](https://user-images.githubusercontent.com/5943484/84572242-0e50cf80-ad99-11ea-8b86-b276c1fa3755.jpg)

**Comment by lkurzyniec** [comment]
@weihan1394 works fine for me
![image](https://user-images.githubusercontent.com/5943484/84575322-92608280-adac-11ea-9edf-4d83f33d4542.png)
here is the branch: https://github.com/lkurzyniec/netcore-boilerplate/tree/test/postgres
or commit: https://github.com/lkurzyniec/netcore-boilerplate/commit/4d394408395b239a7b6a873f87542cff6c405cee

**Comment by lkurzyniec** [comment]
@weihan1394 here https://github.com/weihan1394/ShippingService/blob/7ed5b0ebc87da794d825cb28dab438cbfb07ced3/src/ShippingService.Core/Services/ShippingRateService.cs#L25 you should inject interface instead of class

**Comment by weihan1394** [comment]
@lkurzyniec Thank you for your help once again. Just notice for my mistake. However, when I try to insert the data to the database it seems like the "ShippingExpressContext" is dropped before I save the data to the database.

`System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ShippingExpressContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.AddAsync[TEntity](TEntity entity, CancellationToken cancellationToken)`

![image](https://user-images.githubusercontent.com/7189650/84614554-132c9500-aef9-11ea-9fd3-c540f09a5165.png)

**Comment by lkurzyniec** [comment]
@weihan1394 it looks like something dispose dbcontext and then you have tried to use it one more time. as a very quick fix try to change registration of dbcontext from `AddDbContextPool()` to `AddDbContext()`.

**Comment by weihan1394** [comment]
Hmm, I tried changing it to `AddDbContext()` but it seems to be still having the same problem. I also tried changing the repository to a synchronous method but it still didn't manage to resolve it as I thought the asynchronous is the one that is causing the dispose to happen itself. 😢

I am currently using the 'chore/test-dependency-injection' branch to test. 
![image](https://user-images.githubusercontent.com/7189650/84683878-71459080-af6a-11ea-9290-4c11d65c754b.png)

[ShippingServiceRepository.cs](https://github.com/weihan1394/ShippingService/blob/chore/test-dependency-injection/src/ShippingService.Core/Repositories/ShippingExpressRepository.cs)

**Comment by lkurzyniec** [comment]
@weihan1394 can you provide me a test case (file(s)) that you're trying to submit/upload through that api?

**Comment by weihan1394** [comment]
@lkurzyniec This is the test file I am using. 
[test_file.xlsx](https://github.com/lkurzyniec/netcore-boilerplate/files/4783812/test_file.xlsx)

**Comment by weihan1394** [comment]
Hi @lkurzyniec I have resolved the issue and will close this issue. Thank you.

**Comment by lkurzyniec** [comment]
@weihan1394 happy to hear that. cheers
