### ISSUE TITLE
docker compose not working ? 

### ISSUE THREAD

**Issue by punkouter23** [lkurzyniec/netcore-boilerplate#164]
> [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                                                                                      0.2s
 => CANCELED [build 1/8] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7                                 0.0s
 => => resolve mcr.microsoft.com/dotnet/sdk:7.0@sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7                                                0.0s   > => sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7 1.82kB / 1.82kB                                                                         0.0s
 => => sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7 1.82kB / 1.82kB                                                                         0.0s   > => sha256:a1acc0e30787b76c634d2482aaa13e92a0ec9643abccada4c38e1eda26557981 7.16kB / 7.16kB                                                                         0.0s
 => => sha256:a2d065a38471c9e4709745012f2fca26a715cfc6975eef5611c65000d4943259 2.01kB / 2.01kB                                                                         0.0s   > => resolve mcr.microsoft.com/dotnet/aspnet:7.0@sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf                                             0.0s
 => => sha256:a1acc0e30787b76c634d2482aaa13e92a0ec9643abccada4c38e1eda26557981 7.16kB / 7.16kB                                                                         0.0s   > => sha256:093335d9beee34ed3c51a18def2161f62c15da8b3a21143f2478d10d70d3e3c6 1.37kB / 1.37kB                                                                         0.0s
 => CANCELED [final 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf                              0.0s   > ERROR [internal] load build context                                                                                                                                0.0s
 => => resolve mcr.microsoft.com/dotnet/aspnet:7.0@sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf                                             0.0s  => => resolve mcr.microsoft.com/dotnet/sdk:7.0@sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7                                                0.0s
 => => sha256:1015914ba9e3d3ab350f522aa446d17d7ee68190e431a25c0c11e678081327c7 1.82kB / 1.82kB                                                                         0.0s
 => => sha256:a2d065a38471c9e4709745012f2fca26a715cfc6975eef5611c65000d4943259 2.01kB / 2.01kB                                                                         0.0s
 => => sha256:a1acc0e30787b76c634d2482aaa13e92a0ec9643abccada4c38e1eda26557981 7.16kB / 7.16kB                                                                         0.0s
 => CANCELED [final 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf                              0.0s
 => => resolve mcr.microsoft.com/dotnet/aspnet:7.0@sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf                                             0.0s
 => => sha256:d43cb7cae013b5411fb9c1065d126585f50b6ccfc42d4c6d8e4e4114eadfb7cf 1.82kB / 1.82kB                                                                         0.0s
 => => sha256:093335d9beee34ed3c51a18def2161f62c15da8b3a21143f2478d10d70d3e3c6 1.37kB / 1.37kB                                                                         0.0s
 => => sha256:ee7a11c84975fa708fcfc261370e09b844f99fd3a3fc7541ed7c08915eb5112c 3.25kB / 3.25kB                                                                         0.0s
 => ERROR [internal] load build context                                                                                                                                0.0s
 => => transferring context: 124B                                                                                                                                      0.0s
------
 > [internal] load build context:
failed to solve: error from sender: readdir: open C:\Downloads\netcore-boilerplate\src\*: The filename, directory name, or volume label syntax is incorrect.
PS C:\Downloads\netcore-boilerplate>

**Comment by lkurzyniec** [comment]
It's working fine. I'm guessing the problem could be line endings. Try to google solution for that. My top results:
- https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/
- https://stackoverflow.com/questions/65320180/issue-with-line-endings-when-developing-on-a-windows-but-running-on-a-unix-docke
