### ISSUE TITLE
Is't possible database first?

### ISSUE THREAD

**Issue by biapar** [lkurzyniec/netcore-boilerplate#18]
Is't possible database first?

**Comment by lkurzyniec** [comment]
It is database first approach. This is why I have `HappyCode.NetCoreBoilerplate.Db` project, to run modification scripts

**Comment by biapar** [comment]
Ok. You mean that we extract the database from staging with scripts and then we use the sql file. 
With is't the approach if I have a running db and I want to attach it with your template?

**Comment by lkurzyniec** [comment]
You can do it either manually or automagically.

* Manually
    * Declare db models here: https://github.com/lkurzyniec/netcore-boilerplate/tree/master/src/HappyCode.NetCoreBoilerplate.Core/Models
    * update db context file
    * update `OnModelCreating()` method 

* Automagic
    * scaffold your existing db, here you can find my example: https://github.com/lkurzyniec/netcore-boilerplate/blob/master/db/mssql/scaffold-mssql-db.bat

**Comment by lkurzyniec** [comment]
I'm assuming that the issue is resolved, question answered, so I'm closing it.
