### ISSUE TITLE
Redundant CorellationId parameter in controler's methods

### ISSUE THREAD

**Issue by cezarypiatek** [lkurzyniec/netcore-boilerplate#5]
What is the purpose of adding `[FromHeader(Name = "x-correlation-id")] string correlationId = null,` to every controller's method? At first, it seems to be redundant and indeed - a boilerplate code that should be somehow handled globally (if really is necessary).

**Comment by lkurzyniec** [comment]
You have right, we don't need it, it works out of the box without the header. Thanks for pointing it out.
![image](https://user-images.githubusercontent.com/5943484/68660337-40672e00-0539-11ea-80ac-f510dfbe76b0.png)
